import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:device_info_plus/device_info_plus.dart';
import 'package:package_info_plus/package_info_plus.dart';

import '../../../shared/widgets/common_widgets.dart';
import '../../../core/app.dart';

class DeviceRegistrationScreen extends ConsumerStatefulWidget {
  const DeviceRegistrationScreen({super.key});

  @override
  ConsumerState<DeviceRegistrationScreen> createState() => _DeviceRegistrationScreenState();
}

class _DeviceRegistrationScreenState extends ConsumerState<DeviceRegistrationScreen> {
  final _formKey = GlobalKey<FormState>();
  final _serverUrlController = TextEditingController();
  final _deviceNameController = TextEditingController();
  final _usernameController = TextEditingController();
  final _registrationCodeController = TextEditingController();
  
  bool _isLoading = false;
  bool _autoGeneratedName = true;
  String? _errorMessage;
  String? _deviceInfo;

  @override
  void initState() {
    super.initState();
    _initializeForm();
  }

  @override
  void dispose() {
    _serverUrlController.dispose();
    _deviceNameController.dispose();
    _usernameController.dispose();
    _registrationCodeController.dispose();
    super.dispose();
  }

  Future<void> _initializeForm() async {
    try {
      // Load saved server URL
      final serverUrl = await App.getServerUrl();
      _serverUrlController.text = serverUrl;
      
      // Get device information
      await _getDeviceInfo();
      
      // Generate default device name
      if (_autoGeneratedName) {
        await _generateDeviceName();
      }
    } catch (e) {
      App.logger.e('Failed to initialize form: $e');
    }
  }

  Future<void> _getDeviceInfo() async {
    try {
      final deviceInfo = DeviceInfoPlugin();
      final packageInfo = await PackageInfo.fromPlatform();
      
      String info = '';
      
      if (Theme.of(context).platform == TargetPlatform.android) {
        final androidInfo = await deviceInfo.androidInfo;
        info = 'Android ${androidInfo.version.release}\n'
               'Model: ${androidInfo.model}\n'
               'App: ${packageInfo.version}';
      } else if (Theme.of(context).platform == TargetPlatform.iOS) {
        final iosInfo = await deviceInfo.iosInfo;
        info = 'iOS ${iosInfo.systemVersion}\n'
               'Model: ${iosInfo.model}\n'
               'App: ${packageInfo.version}';
      } else {
        info = 'Platform: ${Theme.of(context).platform.name}\n'
               'App: ${packageInfo.version}';
      }
      
      setState(() {
        _deviceInfo = info;
      });
    } catch (e) {
      App.logger.e('Failed to get device info: $e');
    }
  }

  Future<void> _generateDeviceName() async {
    try {
      final deviceInfo = DeviceInfoPlugin();
      String deviceName = 'NoodleControl Device';
      
      if (Theme.of(context).platform == TargetPlatform.android) {
        final androidInfo = await deviceInfo.androidInfo;
        deviceName = '${androidInfo.model} NoodleControl';
      } else if (Theme.of(context).platform == TargetPlatform.iOS) {
        final iosInfo = await deviceInfo.iosInfo;
        deviceName = '${iosInfo.name} NoodleControl';
      }
      
      _deviceNameController.text = deviceName;
    } catch (e) {
      App.logger.e('Failed to generate device name: $e');
      _deviceNameController.text = 'NoodleControl Device';
    }
  }

  Future<void> _registerDevice() async {
    if (!_formKey.currentState!.validate()) {
      return;
    }

    setState(() {
      _isLoading = true;
      _errorMessage = null;
    });

    try {
      // Save server URL
      await App.saveServerUrl(_serverUrlController.text.trim());
      
      // TODO: Implement actual device registration logic
      // For now, simulate a successful registration
      await Future.delayed(const Duration(seconds: 2));
      
      // Generate a unique device ID
      final deviceId = 'device_${DateTime.now().millisecondsSinceEpoch}';
      await App.saveDeviceId(deviceId);
      
      // Save a mock token
      await App.saveToken('mock_token_${DateTime.now().millisecondsSinceEpoch}');
      
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('Device registered successfully!'),
            backgroundColor: Colors.green,
          ),
        );
        
        // Navigate to dashboard
        context.go('/dashboard');
      }
    } catch (e) {
      App.logger.e('Device registration failed: $e');
      setState(() {
        _errorMessage = 'Registration failed: ${e.toString()}';
      });
    } finally {
      if (mounted) {
        setState(() {
          _isLoading = false;
        });
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: NoodleAppBar(
        title: 'Register Device',
        automaticallyImplyLeading: true,
      ),
      body: SafeArea(
        child: SingleChildScrollView(
          padding: const EdgeInsets.all(24.0),
          child: Form(
            key: _formKey,
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: [
                const SizedBox(height: 20),
                
                // Introduction text
                Text(
                  'Register this device with your NoodleControl server to enable remote management.',
                  style: Theme.of(context).textTheme.bodyMedium?.copyWith(
                    color: Theme.of(context).colorScheme.onSurfaceVariant,
                  ),
                ),
                
                const SizedBox(height: 24),
                
                // Server URL field
                TextFormField(
                  controller: _serverUrlController,
                  decoration: const InputDecoration(
                    labelText: 'Server URL',
                    hintText: 'ws://localhost:8080',
                    prefixIcon: Icon(Icons.link),
                  ),
                  keyboardType: TextInputType.url,
                  validator: (value) {
                    if (value == null || value.trim().isEmpty) {
                      return 'Please enter a server URL';
                    }
                    return null;
                  },
                ),
                
                const SizedBox(height: 16),
                
                // Device name field
                TextFormField(
                  controller: _deviceNameController,
                  decoration: InputDecoration(
                    labelText: 'Device Name',
                    hintText: 'Enter a name for this device',
                    prefixIcon: const Icon(Icons.devices),
                    suffixIcon: _autoGeneratedName
                        ? IconButton(
                            icon: const Icon(Icons.edit),
                            onPressed: () {
                              setState(() {
                                _autoGeneratedName = false;
                              });
                              _deviceNameController.selection = TextSelection(
                                baseOffset: 0,
                                extentOffset: _deviceNameController.text.length,
                              );
                            },
                          )
                        : null,
                  ),
                  keyboardType: TextInputType.text,
                  textInputAction: TextInputAction.next,
                  validator: (value) {
                    if (value == null || value.trim().isEmpty) {
                      return 'Please enter a device name';
                    }
                    return null;
                  },
                  enabled: !_autoGeneratedName,
                ),
                
                const SizedBox(height: 16),
                
                // Username field
                TextFormField(
                  controller: _usernameController,
                  decoration: const InputDecoration(
                    labelText: 'Your Name',
                    hintText: 'Enter your name',
                    prefixIcon: Icon(Icons.person),
                  ),
                  keyboardType: TextInputType.text,
                  textInputAction: TextInputAction.next,
                  validator: (value) {
                    if (value == null || value.trim().isEmpty) {
                      return 'Please enter your name';
                    }
                    return null;
                  },
                ),
                
                const SizedBox(height: 16),
                
                // Registration code field
                TextFormField(
                  controller: _registrationCodeController,
                  decoration: const InputDecoration(
                    labelText: 'Registration Code (Optional)',
                    hintText: 'Enter registration code if provided',
                    prefixIcon: Icon(Icons.vpn_key),
                  ),
                  keyboardType: TextInputType.text,
                  textInputAction: TextInputAction.done,
                  onFieldSubmitted: (_) => _registerDevice(),
                ),
                
                const SizedBox(height: 24),
                
                // Device info
                if (_deviceInfo != null) ...[
                  Container(
                    width: double.infinity,
                    padding: const EdgeInsets.all(16),
                    decoration: BoxDecoration(
                      color: Theme.of(context).colorScheme.surfaceVariant,
                      borderRadius: BorderRadius.circular(12),
                    ),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Row(
                          children: [
                            Icon(
                              Icons.info_outline,
                              size: 20,
                              color: Theme.of(context).colorScheme.onSurfaceVariant,
                            ),
                            const SizedBox(width: 8),
                            Text(
                              'Device Information',
                              style: Theme.of(context).textTheme.titleSmall?.copyWith(
                                fontWeight: FontWeight.bold,
                                color: Theme.of(context).colorScheme.onSurfaceVariant,
                              ),
                            ),
                          ],
                        ),
                        const SizedBox(height: 8),
                        Text(
                          _deviceInfo!,
                          style: Theme.of(context).textTheme.bodySmall?.copyWith(
                            color: Theme.of(context).colorScheme.onSurfaceVariant,
                          ),
                        ),
                      ],
                    ),
                  ),
                  const SizedBox(height: 24),
                ],
                
                // Error message
                if (_errorMessage != null) ...[
                  Container(
                    padding: const EdgeInsets.all(12),
                    decoration: BoxDecoration(
                      color: Theme.of(context).colorScheme.errorContainer,
                      borderRadius: BorderRadius.circular(8),
                    ),
                    child: Row(
                      children: [
                        Icon(
                          Icons.error,
                          color: Theme.of(context).colorScheme.error,
                          size: 20,
                        ),
                        const SizedBox(width: 8),
                        Expanded(
                          child: Text(
                            _errorMessage!,
                            style: TextStyle(
                              color: Theme.of(context).colorScheme.onErrorContainer,
                            ),
                          ),
                        ),
                      ],
                    ),
                  ),
                  const SizedBox(height: 16),
                ],
                
                // Register button
                ActionButton(
                  label: 'Register Device',
                  onPressed: _registerDevice,
                  isLoading: _isLoading,
                ),
                
                const SizedBox(height: 24),
                
                // Sign in link
                Center(
                  child: TextButton(
                    onPressed: () => context.go('/auth/login'),
                    child: Text(
                      'Already have an account? Sign In',
                      style: TextStyle(
                        color: Theme.of(context).colorScheme.primary,
                      ),
                    ),
                  ),
                ),
                
                const SizedBox(height: 32),
                
                // Help section
                Container(
                  padding: const EdgeInsets.all(16),
                  decoration: BoxDecoration(
                    color: Theme.of(context).colorScheme.surfaceVariant,
                    borderRadius: BorderRadius.circular(12),
                  ),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        'Registration Help',
                        style: Theme.of(context).textTheme.titleSmall?.copyWith(
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                      const SizedBox(height: 8),
                      Text(
                        '1. Make sure your NoodleControl server is running\n'
                        '2. Enter the server URL (e.g., ws://localhost:8080)\n'
                        '3. Provide a unique name for this device\n'
                        '4. Enter your name for identification\n'
                        '5. Optionally enter a registration code if required',
                        style: Theme.of(context).textTheme.bodySmall,
                      ),
                    ],
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}