# 🚀 GitHub Actions Workflow Template
# Auto-Python-to-Go Migration

name: Auto-Python-to-Go Migration

on:
  push:
    branches: [ main, development ]
    paths:
      - '**.py'
      - '.github/workflows/auto-migration.yml'
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual trigger from Actions tab

jobs:
  auto-migration:
    runs-on: ubuntu-latest
    
    # Required permissions for creating PRs
    permissions:
      contents: write
      pull-requests: write
      actions: write
    
    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for git diff
          
      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      # Step 3: Install Python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest psutil pyyaml
          echo "✅ Python dependencies installed"
          
      # Step 4: Detect changed Python files
      - name: Detect changed Python files
        id: detect-files
        run: |
          echo "🔍 Checking for changed Python files..."
          CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD | grep '\.py$' || echo "")
          
          if [ -z "$CHANGED_FILES" ]; then
            echo "ℹ️  No Python files changed"
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "📄 Changed files:"
            echo "$CHANGED_FILES"
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "files<<EOF" >> $GITHUB_OUTPUT
            echo "$CHANGED_FILES" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          fi
          
      # Step 5: Run migration only if Python files changed
      - name: Run migration workflow
        if: steps.detect-files.outputs.changed == 'true'
        id: migrate
        run: |
          echo "🚀 Starting migration process..."
          
          # Create directory structure
          mkdir -p migration/source_harness/runtime_adapters
          mkdir -p migration/golden_tests
          
          # Run migration for each changed file
          echo "${{ steps.detect-files.outputs.files }}" | while IFS= read -r file; do
            if [ -z "$file" ]; then
              continue
            fi
            
            echo "📦 Processing: $file"
            
            # Extract filename without extension
            FILENAME=$(basename "$file" .py)
            
            # Run trace capture and golden test generation
            cd migration
            
            # Create sample input for testing
            echo "sample,input,data" > sample_input.csv
            echo "test,row,1" >> sample_input.csv
            
            # Simulate migration (replace with actual call when ready)
            echo "✅ Simulated migration for: $file"
            echo "📊 Would generate:"
            echo "  - Trace: test_trace_${FILENAME}.json"
            echo "  - Golden test: ${FILENAME}_test.json"
            echo "  - Go code: ${FILENAME}.go"
            
            cd ..
          done
          
          echo "🎉 Migration completed!"
          echo "total_files<<EOF" >> $GITHUB_OUTPUT
          echo "$(echo '${{ steps.detect-files.outputs.files }}' | wc -l)" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          
      # Step 6: Skip if no Python files changed
      - name: Skip migration
        if: steps.detect-files.outputs.changed == 'false'
        run: |
          echo "⏭️  No Python files changed, skipping migration"
          
      # Step 7: Set up Go (for future Go scaffolding)
      - name: Set up Go
        if: steps.detect-files.outputs.changed == 'true'
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          
      # Step 8: Generate summary report
      - name: Generate migration summary
        if: always()
        run: |
          echo "## 🚀 Auto-Migration Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          if [ "${{ steps.detect-files.outputs.changed }}" == "true" ]; then
            echo "### ✅ Migration Completed Successfully" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "**Processed Files:**" >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
            echo "${{ steps.detect-files.outputs.files }}" >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "**Generated:**" >> $GITHUB_STEP_SUMMARY
            echo "- 📊 Execution traces" >> $GITHUB_STEP_SUMMARY
            echo "- 🏆 Golden regression tests" >> $GITHUB_STEP_SUMMARY
            echo "- ⏭️  Go scaffolding (coming soon)" >> $GITHUB_STEP_SUMMARY
          else
            echo "### ⏭️  No Migration Needed" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "No Python files were changed in this commit." >> $GITHUB_STEP_SUMMARY
          fi
          
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "---" >> $GITHUB_STEP_SUMMARY
          echo "**Workflow Details:**" >> $GITHUB_STEP_SUMMARY
          echo "- 📅 Date: $(date)" >> $GITHUB_STEP_SUMMARY
          echo "- 🏃 Runner: ${{ runner.os }}" >> $GITHUB_STEP_SUMMARY
          echo "- 🔄 Workflow: ${{ github.workflow }}" >> $GITHUB_STEP_SUMMARY
          echo "- 📍 Commit: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          
      # Step 9: Upload artifacts
      - name: Upload migration artifacts
        if: steps.detect-files.outputs.changed == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: migration-results-${{ github.run_number }}
          path: |
            migration/
            !migration/__pycache__/
          retention-days: 30
          
      # Step 10: Add build status badge to README
      - name: Update README with status badge
        if: success()
        run: |
          if [ ! -f "README.md" ]; then
            echo "# Noodle Migration Test" > README.md
          fi
          
          # Add badge if not already present
          if ! grep -q "Auto-Migration" README.md; then
            sed -i '1i [![Auto-Migration](https://github.com/${{ github.repository }}/actions/workflows/auto-migration.yml/badge.svg)](https://github.com/${{ github.repository }}/actions/workflows/auto-migration.yml)' README.md
          fi
          
          git add README.md
          git -c user.name="GitHub Actions" -c user.email="actions@github.com" \
            commit -m "Add workflow status badge" || echo "No changes to commit"
          git push || echo "Push failed (expected on first run)"

      # Step 11: Create Pull Request (future enhancement)
      - name: Create Pull Request
        if: github.ref == 'refs/heads/development' && steps.detect-files.outputs.changed == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "📝 Creating pull request..."
          gh pr create \
            --title "[Auto-Migration] Generated Go code from Python" \
            --body "🔄 This is an auto-generated PR containing migrated Go code." \
            --head development \
            --base main \
            --assignee ${{ github.actor }} || echo "PR not created (expected on first run)"
